-- ED-175-AWS

INSERT INTO genre (genre_name, genre_active) VALUES
('Rock', TRUE),
('Pop', TRUE),
('Hip-Hop', TRUE),
('Jazz', TRUE),
('Classical', TRUE),
('Electronic', TRUE),
('Indie', TRUE),
('Metal', TRUE),
('Country', TRUE),
('Soul', TRUE),
('News', TRUE),
('Tech', TRUE),
('Comedy', TRUE),
('True Crime', TRUE),
('Society', TRUE),
('History', TRUE),
('Science', TRUE),
('Sports', TRUE),
('Business', TRUE),
('Education', TRUE),
('Vlog', TRUE),
('Gaming', TRUE),
('How-To', TRUE),
('Documentary', TRUE),
('Travel', TRUE),
('Music Video', TRUE),
('Animation', TRUE),
('Review', TRUE),
('Shorts', TRUE),
('Live', TRUE);